services:

  # *************************************************************** #
  simulator:
    image: zeyadharoun/digital-twin-simulator:latest
    environment:
      - VROOM_URL=http://194.28.122.68:3000
      - ELASTICSEARCH_URL=http://194.28.122.68:9200
      - STREAMS_URL=http://sample-address:4001
    volumes:
      - cache-volume:/app/.cache
    ports:
      - 4000:4000
    depends_on:
      sample-address:
        condition: service_started
    networks:
      - app-network

  # *************************************************************** #
  visualisation:
    image: zeyadharoun/digital-twin-visualization:latest
    ports:
      - 3000:80
    depends_on:
      simulator:
          condition: service_started
    networks:
      - app-network

  # *************************************************************** #
  sample-address:
    image: zeyadharoun/digital-twin-sample-address:latest
    environment:
      - PELIAS_HOSTNAME=194.28.122.68:9200
    ports:
      - 4001:4001
    networks:
      - app-network

volumes:
  cache-volume:


networks:
  app-network:
    driver: bridge